export const EMAIL_APPROVAL_TOKEN_BRAND = "al_rev";
export const EMAIL_APPROVAL_TOKEN_ID_LENGTH = 16;
export const EMAIL_APPROVAL_TOKEN_SECRET_BYTES = 32;
export const EMAIL_APPROVAL_TOKEN_MIN_LENGTH = 40;
