import type { DemoScenario } from "./types";

export const FEATURED_SCENARIOS: DemoScenario[] = [
  {
    id: "sim-lead-researcher",
    templateSlug: "lead-researcher",
    title: "Lead Researcher simulation",
    description: "Research a sample company and produce a lead summary. No outreach is sent.",
    whatItDoes: "Looks up sample research notes and drafts a lead brief.",
    whatItWillNotDo: "Will not email, call, or write to a real CRM.",
    mode: "simulation",
    riskLevel: "low",
    tools: ["web_search"],
    inputFields: [
      {
        id: "company",
        label: "Company name",
        placeholder: "Northwind Analytics",
        example: "Northwind Analytics",
      },
    ],
    actions: [
      {
        id: "research-company",
        label: "Research company",
        description: "Simulate enrichment and a lead summary.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "web_search",
        simulatedResult:
          "Sample brief: Northwind Analytics (B2B analytics). Fit score 78/100. Suggested next step: draft a personalized note — not sent.",
      },
    ],
    expectedSteps: [
      { id: "trigger", label: "Trigger" },
      { id: "validate", label: "Validate company" },
      { id: "research", label: "Research approved sources" },
      { id: "extract", label: "Extract facts" },
      { id: "score", label: "Score lead" },
      { id: "summary", label: "Generate summary" },
      { id: "save", label: "Save simulation result" },
    ],
  },
  {
    id: "sim-cold-email-drafter",
    templateSlug: "cold-email-drafter",
    title: "Cold Email Drafter simulation",
    description: "Draft a sample outreach email. Nothing is sent.",
    whatItDoes: "Writes a draft from the lead fields you enter.",
    whatItWillNotDo: "Will not send email through Gmail, SMTP, or any provider.",
    mode: "simulation",
    riskLevel: "medium",
    tools: ["send_email"],
    inputFields: [
      {
        id: "lead",
        label: "Lead information",
        placeholder: "Priya at Northwind, VP Sales, interested in reporting",
        example: "Priya at Northwind, VP Sales",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "draft-email",
        label: "Generate draft",
        description: "Create a sample email draft for review.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "ai_generation",
        simulatedResult:
          "Draft subject: Quick idea for Northwind’s reporting stack. Body stored as a draft only.",
      },
      {
        id: "send-draft-preview",
        label: "Preview send path",
        description: "Show what a send would look like. Requires approval; still not sent.",
        riskLevel: "high",
        requiresApproval: true,
        simulatedTool: "send_email",
        simulatedResult: "Send path previewed. No message left the sandbox.",
      },
    ],
    expectedSteps: [
      { id: "input", label: "Input lead" },
      { id: "validate", label: "Validate fields" },
      { id: "draft", label: "Generate draft" },
      { id: "safety", label: "Safety / content check" },
      { id: "review", label: "Human review" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-customer-support-agent",
    templateSlug: "customer-support-agent",
    title: "Customer Support Agent simulation",
    description: "Answer a sample question from a knowledge-base snippet.",
    whatItDoes: "Drafts a reply from sample help content.",
    whatItWillNotDo: "Will not email or message a real customer.",
    mode: "simulation",
    riskLevel: "low",
    tools: ["send_email"],
    inputFields: [
      {
        id: "question",
        label: "Customer question",
        placeholder: "Where is my order #4821?",
        example: "Where is my order #4821?",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "draft-reply",
        label: "Draft support reply",
        description: "Answer from sample knowledge-base text.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "ai_generation",
        simulatedResult:
          "Sample KB: Order #4821 shipped yesterday. Suggested reply drafted — not sent.",
      },
    ],
    expectedSteps: [
      { id: "intake", label: "Receive question" },
      { id: "kb", label: "Search sample knowledge base" },
      { id: "draft", label: "Draft answer" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-meeting-notes-agent",
    templateSlug: "meeting-notes-agent",
    title: "Meeting Notes Agent simulation",
    description: "Summarize a sample transcript into notes and actions.",
    whatItDoes: "Extracts decisions and action items from sample text.",
    whatItWillNotDo: "Will not write to calendars or notify attendees.",
    mode: "simulation",
    riskLevel: "low",
    tools: ["send_email"],
    inputFields: [
      {
        id: "transcript",
        label: "Sample meeting transcript",
        placeholder: "Alex: Let’s ship the billing fix Friday. Sam: I’ll own QA.",
        example: "Alex: Let’s ship Friday. Sam: I’ll own QA.",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "summarize",
        label: "Summarize meeting",
        description: "Produce notes and action items from the sample transcript.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "ai_summarize",
        simulatedResult: "Summary: Ship billing fix Friday. Action: Sam owns QA.",
      },
    ],
    expectedSteps: [
      { id: "input", label: "Load transcript" },
      { id: "extract", label: "Extract decisions" },
      { id: "actions", label: "List action items" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-invoice-extractor",
    templateSlug: "invoice-extractor",
    title: "Invoice Extractor simulation",
    description: "Extract fields from a sample invoice. Nothing is filed.",
    whatItDoes: "Parses sample invoice text into structured fields.",
    whatItWillNotDo: "Will not submit, pay, or file the invoice.",
    mode: "simulation",
    riskLevel: "low",
    tools: ["read_document"],
    inputFields: [
      {
        id: "invoice",
        label: "Sample invoice",
        placeholder: "Invoice INV-1042 · Acme · ₹18,400 · Due 12 Oct",
        example: "INV-1042 · Acme · ₹18,400",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "extract-fields",
        label: "Extract invoice fields",
        description: "Return structured sample fields.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "ai_extract",
        simulatedResult: "vendor=Acme; number=INV-1042; amount=18400 INR; status=extracted only.",
      },
    ],
    expectedSteps: [
      { id: "input", label: "Load sample invoice" },
      { id: "extract", label: "Extract fields" },
      { id: "review", label: "Show structured result" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-code-review-agent",
    templateSlug: "code-review-agent",
    title: "Code Review Agent simulation",
    description: "Review a sample diff. The repository is not changed.",
    whatItDoes: "Returns simulated findings on the pasted diff.",
    whatItWillNotDo: "Will not push, comment on GitHub, or modify code.",
    mode: "simulation",
    riskLevel: "low",
    tools: ["http_request"],
    inputFields: [
      {
        id: "diff",
        label: "Sample code diff",
        placeholder: "+ if (user.role === 'admin') allow();",
        example: "+ if (user.role === 'admin') allow();",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "review-diff",
        label: "Review sample diff",
        description: "Return simulated review comments.",
        riskLevel: "low",
        requiresApproval: false,
        simulatedTool: "ai_reasoning",
        simulatedResult: "Finding: privilege check may be too broad. No files were changed.",
      },
    ],
    expectedSteps: [
      { id: "input", label: "Load diff" },
      { id: "scan", label: "Scan for issues" },
      { id: "report", label: "Report findings" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-ai-safety-monitor",
    templateSlug: "ai-safety-monitor",
    title: "AI Safety Monitor simulation",
    description: "Classify a sample agent event. This is not live production traffic.",
    whatItDoes: "Labels the event allowed, warning, or blocked using sample rules.",
    whatItWillNotDo: "Does not monitor a real production agent unless you connect one later.",
    mode: "simulation",
    riskLevel: "medium",
    tools: ["send_email"],
    inputFields: [
      {
        id: "event",
        label: "Sample agent event",
        placeholder: "Agent requested delete_customer_database",
        example: "Agent requested delete_customer_database",
        multiline: true,
      },
    ],
    actions: [
      {
        id: "classify-event",
        label: "Classify event",
        description: "Apply sample safety rules to the event text.",
        riskLevel: "medium",
        requiresApproval: false,
        simulatedTool: "ai_classification",
        simulatedResult: "Classification: blocked. Reason: destructive database action in sample policy.",
      },
    ],
    expectedSteps: [
      { id: "intake", label: "Receive sample event" },
      { id: "policy", label: "Match sample policy" },
      { id: "classify", label: "Classify" },
      { id: "done", label: "Simulation complete" },
    ],
  },
  {
    id: "sim-refund-request-assistant",
    templateSlug: "refund-request-assistant",
    title: "Refund Request Assistant simulation",
    description: "Check a sample refund against policy. No payment is issued.",
    whatItDoes: "Evaluates amount and customer against sample refund rules.",
    whatItWillNotDo: "Will not call Stripe or any payment provider.",
    mode: "simulation",
    riskLevel: "high",
    tools: ["issue_refund"],
    inputFields: [
      {
        id: "customer",
        label: "Sample customer",
        placeholder: "Asha Patel",
        example: "Asha Patel",
      },
      {
        id: "amount",
        label: "Amount (INR)",
        placeholder: "25000",
        example: "25000",
      },
    ],
    actions: [
      {
        id: "check-policy",
        label: "Check refund policy",
        description: "Simulate a policy decision for the sample amount.",
        riskLevel: "high",
        requiresApproval: true,
        simulatedTool: "issue_refund",
        simulatedResult: "Policy would require approval for this amount. No refund was issued.",
      },
    ],
    expectedSteps: [
      { id: "request", label: "Refund request" },
      { id: "validate", label: "Validate customer" },
      { id: "policy", label: "Check policy" },
      { id: "calc", label: "Calculate simulated result" },
      { id: "approval", label: "Approval checkpoint" },
      { id: "done", label: "Simulation complete" },
    ],
  },
];
