import type { FounderActivityView } from "@/lib/audit/activity-copy";

export const ACTIVITY_DEMO_DISCLAIMER =
  "Simulated audit trail — no real agent is connected yet. These events show how Wave records agent actions.";

function demoTimestamp(hour: number, minute: number, now = Date.now()): string {
  const date = new Date(now);
  date.setHours(hour, minute, 0, 0);
  if (date.getTime() > now) {
    date.setDate(date.getDate() - 1);
  }
  return date.toISOString();
}

function formatTimeDisplay(iso: string): string {
  return new Date(iso).toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  });
}

export function buildDemoActivityViews(now = Date.now()): FounderActivityView[] {
  const events: Array<Omit<FounderActivityView, "relativeTime" | "timeDisplay">> = [
    {
      id: "demo-activity-1",
      agentId: "customer-support-agent",
      agentName: "Support Agent",
      actionLabel: "Check refund status",
      actionType: "other",
      decisionLabel: "Allow",
      message: "Checked refund status for a customer.",
      reason: "Routine status check within automatic safety limits.",
      tone: "allowed",
      timestamp: demoTimestamp(10, 42, now),
      riskLabel: "Low",
      statusLabel: "Completed",
      proposedAction: "Check refund status for order ORD-8821",
      zeltaChecked: {
        policy: "Allowed automatically",
        risk: "Low",
        humanReview: "Not required",
      },
      finalDecisionText: "Completed automatically",
      isSimulated: true,
      whatHappened: "Support Agent checked refund status for a customer.",
      whyDecision: "This was a low-risk read-only action within your automatic limits.",
      actionTaken: "Allowed automatically — the agent could proceed.",
      filterCategory: "allowed",
      details: {
        agent: "Support Agent",
        requestedAction: "Check refund status",
        time: "Today",
        timeFull: formatTimeDisplay(demoTimestamp(10, 42, now)),
        policyResult: "Policy allowed this action automatically.",
        riskResult: "Low risk level for this action.",
        finalDecision: "Allow",
        approvalInfo: null,
        executionResult: "The agent was allowed to complete the action.",
      },
      technical: {
        runtimeEvent: "policy.allow",
        proposalId: null,
        metadata: { simulated: true },
        entityType: "action_proposal",
        entityId: "demo-activity-1",
        actor: "customer-support-agent",
        actorEmail: null,
        ipAddress: null,
        userAgent: null,
        source: "runtime",
      },
    },
    {
      id: "demo-activity-2",
      agentId: "customer-support-agent",
      agentName: "Support Agent",
      actionLabel: "Refund ₹25,000",
      actionType: "refund",
      decisionLabel: "Approval Required",
      message: "Requested approval for ₹25,000 refund.",
      reason: "Refund exceeds the configured approval limit of ₹5,000.",
      tone: "review",
      timestamp: demoTimestamp(10, 39, now),
      riskLabel: "High",
      statusLabel: "Waiting",
      proposedAction: "Refund ₹25,000 to customer CUST-1042",
      zeltaChecked: {
        policy: "Approval required",
        risk: "High",
        humanReview: "Required",
      },
      finalDecisionText: "Waiting for approval",
      isSimulated: true,
      whatHappened: "Support Agent requested approval for ₹25,000 refund.",
      whyDecision: "This refund is above your automatic limit of ₹5,000, so Wave paused it for you.",
      actionTaken: "Paused — waiting for your approval.",
      filterCategory: "review",
      details: {
        agent: "Support Agent",
        requestedAction: "Refund ₹25,000",
        time: "Today",
        timeFull: formatTimeDisplay(demoTimestamp(10, 39, now)),
        policyResult: "Policy requires human approval before continuing.",
        riskResult: "High risk level detected for this action.",
        finalDecision: "Approval Required",
        approvalInfo: "Waiting for a human decision before the agent can continue.",
        executionResult: "Paused — execution has not started yet.",
      },
      technical: {
        runtimeEvent: "policy.review",
        proposalId: "demo-proposal-refund-25k",
        metadata: {
          simulated: true,
          customerId: "CUST-1042",
          amount: 2_500_000,
          currency: "INR",
        },
        entityType: "action_proposal",
        entityId: "demo-activity-2",
        actor: "customer-support-agent",
        actorEmail: null,
        ipAddress: null,
        userAgent: null,
        source: "runtime",
      },
    },
    {
      id: "demo-activity-3",
      agentId: "billing-agent",
      agentName: "Billing Agent",
      actionLabel: "Refund ₹75,000",
      actionType: "refund",
      decisionLabel: "Blocked",
      message: "Blocked a ₹75,000 refund attempt.",
      reason: "Refund amount exceeds the maximum allowed limit.",
      tone: "blocked",
      timestamp: demoTimestamp(10, 35, now),
      riskLabel: "Critical",
      statusLabel: "Blocked",
      proposedAction: "Refund ₹75,000 to customer CUST-2201",
      zeltaChecked: {
        policy: "Blocked",
        risk: "Critical",
        humanReview: "Not applicable",
      },
      finalDecisionText: "Blocked by Wave",
      isSimulated: true,
      whatHappened: "Billing Agent attempted a ₹75,000 refund.",
      whyDecision: "This refund exceeds your maximum allowed limit, so Wave stopped it.",
      actionTaken: "Blocked — the action did not happen.",
      filterCategory: "blocked",
      details: {
        agent: "Billing Agent",
        requestedAction: "Refund ₹75,000",
        time: "Today",
        timeFull: formatTimeDisplay(demoTimestamp(10, 35, now)),
        policyResult: "Policy blocked this action.",
        riskResult: "Critical risk level detected for this action.",
        finalDecision: "Blocked",
        approvalInfo: null,
        executionResult: "The action did not run.",
      },
      technical: {
        runtimeEvent: "policy.block",
        proposalId: "demo-proposal-refund-75k",
        metadata: {
          simulated: true,
          customerId: "CUST-2201",
          amount: 7_500_000,
          currency: "INR",
        },
        entityType: "action_proposal",
        entityId: "demo-activity-3",
        actor: "billing-agent",
        actorEmail: null,
        ipAddress: null,
        userAgent: null,
        source: "runtime",
      },
    },
    {
      id: "demo-activity-4",
      agentId: "customer-support-agent",
      agentName: "Support Agent",
      actionLabel: "Send customer email",
      actionType: "email",
      decisionLabel: "Allow",
      message: "Sent an email to a customer.",
      reason: "Action was within your automatic safety limits.",
      tone: "allowed",
      timestamp: demoTimestamp(10, 31, now),
      riskLabel: "Low",
      statusLabel: "Completed",
      proposedAction: "Send customer email",
      zeltaChecked: {
        policy: "Allowed automatically",
        risk: "Low",
        humanReview: "Not required",
      },
      finalDecisionText: "Completed automatically",
      isSimulated: true,
      whatHappened: "Support Agent sent an email to a customer.",
      whyDecision: "This action was within your automatic safety limits.",
      actionTaken: "Allowed automatically — the agent could proceed.",
      filterCategory: "allowed",
      details: {
        agent: "Support Agent",
        requestedAction: "Send customer email",
        time: "Today",
        timeFull: formatTimeDisplay(demoTimestamp(10, 31, now)),
        policyResult: "Policy allowed this action automatically.",
        riskResult: "Low risk level for this action.",
        finalDecision: "Allow",
        approvalInfo: null,
        executionResult: "The agent was allowed to complete the action.",
      },
      technical: {
        runtimeEvent: "policy.allow",
        proposalId: null,
        metadata: { simulated: true },
        entityType: "action_proposal",
        entityId: "demo-activity-4",
        actor: "customer-support-agent",
        actorEmail: null,
        ipAddress: null,
        userAgent: null,
        source: "runtime",
      },
    },
  ];

  return events.map((event) => ({
    ...event,
    relativeTime: formatTimeDisplay(event.timestamp),
    timeDisplay: formatTimeDisplay(event.timestamp),
  }));
}
