import type { AllowedAgentTool } from "@/lib/xai/parse-agent-build";
import { mapTriggerToRuntime, safetyDefaultsForRisk } from "./safety-defaults";
import type {
  AgentTemplate,
  MarketplaceCategory,
  TemplateRiskLevel,
  TemplateTrigger,
} from "./types";

interface CatalogDraft {
  slug: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  category: MarketplaceCategory;
  icon: string;
  tags: string[];
  riskLevel: TemplateRiskLevel;
  estimatedSetupMinutes: number;
  suggestedIntegrations: string[];
  tools: AllowedAgentTool[];
  defaultInstructions: string;
  exampleTasks: string[];
  defaultTrigger: TemplateTrigger;
  supportsThreshold?: boolean;
  defaultThreshold?: number | null;
  isFeatured?: boolean;
  sortOrder: number;
}

function hydrate(draft: CatalogDraft): AgentTemplate {
  const safety = safetyDefaultsForRisk(draft.riskLevel, draft.tools);
  const triggerType = mapTriggerToRuntime(draft.defaultTrigger);
  return {
    id: draft.slug,
    slug: draft.slug,
    name: draft.name,
    description: draft.shortDescription,
    summary: draft.shortDescription,
    shortDescription: draft.shortDescription,
    longDescription: draft.longDescription,
    icon: draft.icon,
    category: draft.category,
    defaultDescription: draft.longDescription,
    tools: draft.tools,
    triggerType,
    defaultTrigger: draft.defaultTrigger,
    supportsThreshold: draft.supportsThreshold ?? draft.riskLevel !== "low",
    defaultThreshold: draft.defaultThreshold ?? (draft.riskLevel === "low" ? null : 5000),
    tags: draft.tags,
    riskLevel: draft.riskLevel,
    estimatedSetupMinutes: draft.estimatedSetupMinutes,
    suggestedIntegrations: draft.suggestedIntegrations,
    defaultInstructions: draft.defaultInstructions,
    exampleTasks: draft.exampleTasks,
    defaultSafetyPreset: safety.preset,
    defaultToolPermissions: safety.toolPermissions,
    defaultApprovalRules: safety.approvalRules,
    defaultExecutionLimits: safety.executionLimits,
    defaultDataProtection: safety.dataProtection,
    requiresApproval: safety.requiresApproval,
    isFeatured: draft.isFeatured ?? false,
    isPublished: true,
    sortOrder: draft.sortOrder,
  };
}

const DRAFTS: CatalogDraft[] = [
  {
    slug: "lead-researcher",
    name: "Lead Researcher",
    shortDescription: "Finds and qualifies prospects from approved sources.",
    longDescription:
      "Researches companies and contacts using only sources you approve, then scores fit against your ideal customer profile. It drafts a short qualification note and does not email prospects unless you later connect outreach.",
    category: "sales-marketing",
    icon: "Search",
    tags: ["leads", "research", "outbound"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Web search", "CRM"],
    tools: ["query_database"],
    defaultInstructions:
      "Research prospects only from approved public sources. Summarize company, role, and fit. Do not contact anyone. Do not invent contact details.",
    exampleTasks: [
      "Find 10 SaaS companies in India that match our ICP",
      "Qualify this list of domains and flag poor-fit accounts",
    ],
    defaultTrigger: "manual",
    isFeatured: true,
    sortOrder: 1,
  },
  {
    slug: "cold-email-drafter",
    name: "Cold Email Drafter",
    shortDescription: "Writes personalized outreach; approval required before every send.",
    longDescription:
      "Turns research notes into a personalized cold email. Wave requires approval before any message is sent. Bulk send is off.",
    category: "sales-marketing",
    icon: "Mail",
    tags: ["email", "outreach", "approval"],
    riskLevel: "high",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Email"],
    tools: ["send_email", "query_database"],
    defaultInstructions:
      "Draft one personalized email at a time from the provided notes. Do not send until approved. Do not BCC large lists. Do not invent facts about the recipient.",
    exampleTasks: ["Draft an intro email to a VP of Ops at a D2C brand"],
    defaultTrigger: "manual",
    sortOrder: 2,
  },
  {
    slug: "linkedin-outreach-assistant",
    name: "LinkedIn Outreach Assistant",
    shortDescription: "Prepares connection notes and follow-ups; never sends automatically by default.",
    longDescription:
      "Drafts LinkedIn connection notes and follow-ups from a profile summary. Sending stays manual unless you later change permissions.",
    category: "sales-marketing",
    icon: "Users",
    tags: ["linkedin", "outreach", "drafts"],
    riskLevel: "medium",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Web search"],
    tools: ["query_database"],
    defaultInstructions:
      "Write short, specific LinkedIn notes. Do not send messages. Do not scrape private data. Keep a respectful, non-spammy tone.",
    exampleTasks: ["Write a connection note for a founder I met at a meetup"],
    defaultTrigger: "manual",
    sortOrder: 3,
  },
  {
    slug: "sales-call-briefing-agent",
    name: "Sales Call Briefing Agent",
    shortDescription: "Creates company, contact, and meeting briefs.",
    longDescription:
      "Builds a one-page briefing before a sales call: company snapshot, likely pain, recent news, and suggested questions. Read-only by default.",
    category: "sales-marketing",
    icon: "ClipboardList",
    tags: ["sales", "meetings", "briefing"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Web search", "Calendar"],
    tools: ["query_database"],
    defaultInstructions:
      "Produce a concise call brief. Cite only provided or public information. Do not contact the prospect.",
    exampleTasks: ["Brief me on Acme Retail before Thursday’s demo"],
    defaultTrigger: "schedule",
    isFeatured: true,
    sortOrder: 4,
  },
  {
    slug: "crm-cleanup-agent",
    name: "CRM Cleanup Agent",
    shortDescription: "Finds duplicates and missing information; asks before editing records.",
    longDescription:
      "Scans CRM-style records for duplicates and missing fields, then proposes fixes. Updates require your approval.",
    category: "sales-marketing",
    icon: "Database",
    tags: ["crm", "data-quality"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["CRM"],
    tools: ["query_database", "update_crm_record"],
    defaultInstructions:
      "List duplicate or incomplete records and propose a merge or fill-in. Do not edit records until approved. Do not delete records.",
    exampleTasks: ["Find duplicate companies in this export"],
    defaultTrigger: "manual",
    sortOrder: 5,
  },
  {
    slug: "proposal-writer",
    name: "Proposal Writer",
    shortDescription: "Turns sales notes into a proposal draft.",
    longDescription:
      "Converts discovery notes into a structured proposal draft for your review. It does not send the proposal to the customer.",
    category: "sales-marketing",
    icon: "FileText",
    tags: ["proposals", "writing"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Draft a proposal from the notes. Do not invent pricing. Leave placeholders where numbers are missing. Do not email the customer.",
    exampleTasks: ["Turn these discovery notes into a two-page proposal"],
    defaultTrigger: "manual",
    sortOrder: 6,
  },
  {
    slug: "competitor-monitor",
    name: "Competitor Monitor",
    shortDescription: "Tracks approved competitor websites, pricing, and announcements.",
    longDescription:
      "Checks a list of competitor URLs you provide and summarizes pricing or announcement changes. It does not change your site or ads.",
    category: "sales-marketing",
    icon: "Radar",
    tags: ["competitors", "research"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Web search", "HTTP"],
    tools: ["query_database"],
    defaultInstructions:
      "Only visit URLs on the approved list. Summarize changes. Do not log in to competitor accounts. Do not copy copyrighted pages in full.",
    exampleTasks: ["Check these three pricing pages for changes this week"],
    defaultTrigger: "schedule",
    sortOrder: 7,
  },
  {
    slug: "seo-content-planner",
    name: "SEO Content Planner",
    shortDescription: "Builds keyword clusters and content calendars.",
    longDescription:
      "Groups keywords into clusters and proposes a content calendar. Publishing is not enabled.",
    category: "sales-marketing",
    icon: "CalendarRange",
    tags: ["seo", "content"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Web search", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Propose clusters and a calendar. Do not publish. Flag trademark or competitor-brand keyword risks.",
    exampleTasks: ["Build a 30-day blog calendar for invoice automation"],
    defaultTrigger: "manual",
    sortOrder: 8,
  },
  {
    slug: "blog-writer",
    name: "Blog Writer",
    shortDescription: "Creates SEO article drafts; approval required before publishing.",
    longDescription:
      "Writes an article draft from an outline and keywords. Publishing or posting live requires your approval. The agent starts paused.",
    category: "sales-marketing",
    icon: "PenLine",
    tags: ["blog", "seo", "publishing"],
    riskLevel: "high",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["CMS", "Documents"],
    tools: ["send_email", "query_database"],
    defaultInstructions:
      "Write a draft article. Do not publish. Do not scrape paywalled content. Mark claims that need a source.",
    exampleTasks: ["Draft a 1,000-word post on agent approvals for founders"],
    defaultTrigger: "manual",
    sortOrder: 9,
  },
  {
    slug: "social-media-planner",
    name: "Social Media Planner",
    shortDescription: "Creates social-post drafts and a publishing schedule.",
    longDescription:
      "Produces a week of social drafts and a schedule. Auto-posting is off.",
    category: "sales-marketing",
    icon: "Share2",
    tags: ["social", "content"],
    riskLevel: "medium",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Social", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Draft posts and a schedule. Do not publish. Avoid exaggerated claims. Keep brand voice professional.",
    exampleTasks: ["Plan 5 LinkedIn posts about our new approval workflow"],
    defaultTrigger: "schedule",
    sortOrder: 10,
  },
  {
    slug: "ad-copy-generator",
    name: "Ad Copy Generator",
    shortDescription: "Produces ad copy variations; cannot launch campaigns by default.",
    longDescription:
      "Writes ad headlines and descriptions for your review. It cannot create or launch ad campaigns.",
    category: "sales-marketing",
    icon: "Megaphone",
    tags: ["ads", "copy"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Ads"],
    tools: ["query_database"],
    defaultInstructions:
      "Produce copy variations only. Do not launch campaigns. Do not spend money. Stay truthful.",
    exampleTasks: ["Write 8 Google ad headlines for Wave agent templates"],
    defaultTrigger: "manual",
    sortOrder: 11,
  },
  {
    slug: "review-response-assistant",
    name: "Review Response Assistant",
    shortDescription: "Drafts replies to customer reviews.",
    longDescription:
      "Drafts public-review replies that stay factual and calm. Posting the reply requires approval.",
    category: "sales-marketing",
    icon: "MessageSquareQuote",
    tags: ["reviews", "support"],
    riskLevel: "medium",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Email", "Reviews"],
    tools: ["send_email"],
    defaultInstructions:
      "Draft a reply. Do not argue. Do not offer refunds unless the policy is provided. Do not post until approved.",
    exampleTasks: ["Draft a reply to this 2-star shipping review"],
    defaultTrigger: "webhook",
    sortOrder: 12,
  },
  {
    slug: "newsletter-creator",
    name: "Newsletter Creator",
    shortDescription: "Converts product updates into newsletter drafts.",
    longDescription:
      "Turns release notes into a newsletter draft. Sending to a list requires approval. Bulk send stays off.",
    category: "sales-marketing",
    icon: "Newspaper",
    tags: ["newsletter", "email"],
    riskLevel: "high",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Email"],
    tools: ["send_email"],
    defaultInstructions:
      "Draft one newsletter. Do not send to a list until approved. Do not add subscribers. Keep claims accurate.",
    exampleTasks: ["Turn this changelog into a customer newsletter"],
    defaultTrigger: "manual",
    sortOrder: 13,
  },
  {
    slug: "influencer-researcher",
    name: "Influencer Researcher",
    shortDescription: "Finds relevant creators and creates outreach lists.",
    longDescription:
      "Builds a research list of creators from public information. Outreach sending is not enabled by default.",
    category: "sales-marketing",
    icon: "Star",
    tags: ["influencers", "research"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Web search"],
    tools: ["query_database"],
    defaultInstructions:
      "List public creator profiles that match the brief. Do not contact them. Do not guess private emails.",
    exampleTasks: ["Find 15 Indian D2C creators in home and kitchen"],
    defaultTrigger: "manual",
    sortOrder: 14,
  },
  {
    slug: "landing-page-copy-auditor",
    name: "Landing Page Copy Auditor",
    shortDescription: "Reviews landing-page copy and suggests conversion improvements.",
    longDescription:
      "Reviews provided copy or a URL you approve and suggests clearer headlines and CTAs. It does not edit the live page.",
    category: "sales-marketing",
    icon: "LineChart",
    tags: ["conversion", "copy"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Web search", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Audit copy for clarity and trust. Do not change production pages. Flag legal or guarantee language that looks overstated.",
    exampleTasks: ["Review this pricing page hero and CTA"],
    defaultTrigger: "manual",
    sortOrder: 15,
  },
  {
    slug: "customer-support-agent",
    name: "Customer Support Agent",
    shortDescription: "Answers questions using only approved knowledge-base sources and escalates uncertainty.",
    longDescription:
      "Answers from your approved help content. If it is unsure, it drafts an escalation instead of guessing.",
    category: "customer-support",
    icon: "Headphones",
    tags: ["support", "knowledge-base"],
    riskLevel: "medium",
    estimatedSetupMinutes: 20,
    suggestedIntegrations: ["Help center", "Email"],
    tools: ["query_database", "send_email"],
    defaultInstructions:
      "Answer only from approved sources. If missing, say you will escalate. Do not invent policy. Do not issue refunds.",
    exampleTasks: ["Answer this question about changing a delivery address"],
    defaultTrigger: "inbox",
    isFeatured: true,
    sortOrder: 16,
  },
  {
    slug: "ticket-triage-agent",
    name: "Ticket Triage Agent",
    shortDescription: "Categorizes, prioritizes, and routes support tickets.",
    longDescription:
      "Labels incoming tickets by topic, urgency, and team. It does not close tickets or message customers automatically.",
    category: "customer-support",
    icon: "Inbox",
    tags: ["tickets", "routing"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Help desk"],
    tools: ["query_database"],
    defaultInstructions:
      "Classify and route. Do not reply to the customer. Do not close tickets. Escalate legal or safety issues.",
    exampleTasks: ["Triage these 20 ticket subjects"],
    defaultTrigger: "webhook",
    sortOrder: 17,
  },
  {
    slug: "refund-request-assistant",
    name: "Refund Request Assistant",
    shortDescription: "Checks policy and drafts a response; approval required for all refunds.",
    longDescription:
      "Compares a request to your refund policy and drafts a response. Every refund action requires approval. Automatic refunds are off.",
    category: "customer-support",
    icon: "Banknote",
    tags: ["refunds", "policy"],
    riskLevel: "high",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Payments", "Email", "CRM"],
    tools: ["issue_refund", "send_email", "query_database"],
    defaultInstructions:
      "Check the written policy. Draft a reply. Never execute a refund until a human approves. Never promise a refund the policy does not allow.",
    exampleTasks: ["Review this refund request against our 7-day policy"],
    defaultTrigger: "webhook",
    supportsThreshold: true,
    defaultThreshold: 5000,
    isFeatured: true,
    sortOrder: 18,
  },
  {
    slug: "order-status-assistant",
    name: "Order Status Assistant",
    shortDescription: "Retrieves shipping and order data in read-only mode.",
    longDescription:
      "Looks up order and shipping status from connected read-only data and drafts a status update.",
    category: "customer-support",
    icon: "Package",
    tags: ["orders", "shipping"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Commerce", "CRM"],
    tools: ["query_database"],
    defaultInstructions:
      "Return order status from provided data only. Do not change orders. Do not cancel shipments.",
    exampleTasks: ["What is the status of order #1042?"],
    defaultTrigger: "inbox",
    sortOrder: 19,
  },
  {
    slug: "faq-builder",
    name: "FAQ Builder",
    shortDescription: "Converts frequent support questions into proposed FAQs.",
    longDescription:
      "Clusters repeated questions and drafts FAQ entries for your review. Publishing is off.",
    category: "customer-support",
    icon: "HelpCircle",
    tags: ["faq", "knowledge"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Help center", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Draft FAQs from tickets. Do not publish. Keep answers limited to confirmed policy.",
    exampleTasks: ["Turn last month’s top questions into 8 FAQs"],
    defaultTrigger: "manual",
    sortOrder: 20,
  },
  {
    slug: "customer-feedback-analyzer",
    name: "Customer Feedback Analyzer",
    shortDescription: "Groups feedback by issue, request, sentiment, and urgency.",
    longDescription:
      "Reads feedback you provide and groups themes. It does not message customers.",
    category: "customer-support",
    icon: "MessagesSquare",
    tags: ["feedback", "analytics"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Documents", "CRM"],
    tools: ["query_database"],
    defaultInstructions:
      "Cluster feedback. Do not contact customers. Do not hide negative themes.",
    exampleTasks: ["Summarize 40 NPS comments by theme"],
    defaultTrigger: "manual",
    sortOrder: 21,
  },
  {
    slug: "churn-risk-detector",
    name: "Churn-Risk Detector",
    shortDescription: "Flags accounts showing negative product or support signals.",
    longDescription:
      "Scores accounts from support and usage signals you supply. It flags risk; it does not cancel accounts or send win-back campaigns unless you later enable that.",
    category: "customer-support",
    icon: "AlertTriangle",
    tags: ["churn", "accounts"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["CRM", "Support"],
    tools: ["query_database", "send_email"],
    defaultInstructions:
      "Flag churn risk with reasons. Do not cancel accounts. Draft outreach only; send only if approved.",
    exampleTasks: ["Which 10 accounts look most at risk this week?"],
    defaultTrigger: "schedule",
    sortOrder: 22,
  },
  {
    slug: "onboarding-guide-agent",
    name: "Onboarding Guide Agent",
    shortDescription: "Guides new users through product setup.",
    longDescription:
      "Walks a new user through setup using your approved onboarding steps. It does not change billing or delete data.",
    category: "customer-support",
    icon: "Map",
    tags: ["onboarding", "activation"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Help center", "Email"],
    tools: ["query_database"],
    defaultInstructions:
      "Guide setup from the approved checklist. Do not access other customers’ data. Do not change plans.",
    exampleTasks: ["Help a new user connect their first agent"],
    defaultTrigger: "manual",
    sortOrder: 23,
  },
  {
    slug: "help-center-article-writer",
    name: "Help Center Article Writer",
    shortDescription: "Drafts support articles for review before publishing.",
    longDescription:
      "Turns a process description into a help article draft. Publishing requires approval.",
    category: "customer-support",
    icon: "BookOpen",
    tags: ["docs", "support"],
    riskLevel: "medium",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Help center", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Draft an article. Do not publish. Use only the process you were given.",
    exampleTasks: ["Write an article on pausing an agent"],
    defaultTrigger: "manual",
    sortOrder: 24,
  },
  {
    slug: "multilingual-support-translator",
    name: "Multilingual Support Translator",
    shortDescription: "Translates support messages while retaining context.",
    longDescription:
      "Translates customer and agent messages while keeping tone. It does not send the translated message until you choose to.",
    category: "customer-support",
    icon: "Languages",
    tags: ["translation", "support"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Email", "Help desk"],
    tools: ["query_database"],
    defaultInstructions:
      "Translate accurately. Do not add new promises. Do not send messages.",
    exampleTasks: ["Translate this Hindi support reply to English"],
    defaultTrigger: "manual",
    sortOrder: 25,
  },
  {
    slug: "executive-assistant",
    name: "Executive Assistant",
    shortDescription: "Summarizes email, prepares daily priorities, and drafts replies.",
    longDescription:
      "Summarizes an inbox snapshot you provide and drafts replies. Sending mail requires approval.",
    category: "operations-productivity",
    icon: "Briefcase",
    tags: ["email", "priorities"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Email", "Calendar"],
    tools: ["send_email", "query_database"],
    defaultInstructions:
      "Summarize and draft. Do not send until approved. Do not delete email. Do not share private threads outside the workspace.",
    exampleTasks: ["Prepare my morning brief from these 12 emails"],
    defaultTrigger: "schedule",
    isFeatured: true,
    sortOrder: 26,
  },
  {
    slug: "meeting-notes-agent",
    name: "Meeting Notes Agent",
    shortDescription: "Produces summaries, decisions, and action items.",
    longDescription:
      "Turns a transcript into decisions and owners. It does not email attendees unless you approve.",
    category: "operations-productivity",
    icon: "NotebookPen",
    tags: ["meetings", "notes"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Documents", "Calendar"],
    tools: ["query_database"],
    defaultInstructions:
      "Capture decisions and actions. Do not invent attendees. Do not send the recap automatically.",
    exampleTasks: ["Summarize this product meeting transcript"],
    defaultTrigger: "manual",
    sortOrder: 27,
  },
  {
    slug: "calendar-scheduling-agent",
    name: "Calendar Scheduling Agent",
    shortDescription: "Proposes meeting times; requires approval before invitations are sent.",
    longDescription:
      "Suggests meeting slots from availability notes. Creating calendar invites requires approval. The agent starts paused.",
    category: "operations-productivity",
    icon: "CalendarPlus",
    tags: ["calendar", "scheduling"],
    riskLevel: "high",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Calendar", "Email"],
    tools: ["create_calendar_event", "send_email"],
    defaultInstructions:
      "Propose times. Do not send invites until approved. Do not overbook. Do not share others’ full calendars.",
    exampleTasks: ["Find 3 slots next week for a 30-minute customer call"],
    defaultTrigger: "manual",
    sortOrder: 28,
  },
  {
    slug: "email-inbox-organizer",
    name: "Email Inbox Organizer",
    shortDescription: "Labels and prioritizes inbox items; never deletes email by default.",
    longDescription:
      "Suggests labels and priority for messages you paste or connect later. Deletion is blocked.",
    category: "operations-productivity",
    icon: "FolderOpen",
    tags: ["email", "organization"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Email"],
    tools: ["query_database"],
    defaultInstructions:
      "Label and prioritize. Never delete. Never send. Never forward outside the workspace.",
    exampleTasks: ["Triage these 25 subject lines"],
    defaultTrigger: "inbox",
    sortOrder: 29,
  },
  {
    slug: "document-summarizer",
    name: "Document Summarizer",
    shortDescription: "Extracts decisions, dates, risks, and tasks from documents.",
    longDescription:
      "Summarizes uploaded or pasted documents into decisions, dates, risks, and tasks.",
    category: "operations-productivity",
    icon: "FileSearch",
    tags: ["documents", "summary"],
    riskLevel: "low",
    estimatedSetupMinutes: 6,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Extract facts from the provided document only. Do not store extra copies of secrets. Redact obvious credentials if present.",
    exampleTasks: ["Summarize this vendor contract for risks"],
    defaultTrigger: "manual",
    sortOrder: 30,
  },
  {
    slug: "sop-generator",
    name: "SOP Generator",
    shortDescription: "Turns a described process into a standard operating procedure.",
    longDescription:
      "Writes a step-by-step SOP from a process description. It does not change production systems.",
    category: "operations-productivity",
    icon: "ListChecks",
    tags: ["sop", "operations"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Write an SOP with steps, owners, and exceptions. Do not execute the process.",
    exampleTasks: ["Turn our refund process into an SOP"],
    defaultTrigger: "manual",
    sortOrder: 31,
  },
  {
    slug: "project-status-reporter",
    name: "Project Status Reporter",
    shortDescription: "Collects updates and prepares weekly reports.",
    longDescription:
      "Turns status notes into a weekly report draft. Sending the report requires approval.",
    category: "operations-productivity",
    icon: "Presentation",
    tags: ["reporting", "projects"],
    riskLevel: "medium",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Email", "Documents"],
    tools: ["send_email", "query_database"],
    defaultInstructions:
      "Draft a status report. Do not send until approved. Do not hide blockers.",
    exampleTasks: ["Write this week’s status from these three updates"],
    defaultTrigger: "schedule",
    sortOrder: 32,
  },
  {
    slug: "task-manager-agent",
    name: "Task Manager Agent",
    shortDescription: "Turns meetings and messages into organized tasks.",
    longDescription:
      "Extracts tasks with owners and due dates. It does not assign work in external tools unless you connect them later.",
    category: "operations-productivity",
    icon: "CheckSquare",
    tags: ["tasks", "productivity"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Create a task list. Do not email assignees automatically. Do not delete existing tasks.",
    exampleTasks: ["Turn this standup transcript into tasks"],
    defaultTrigger: "manual",
    sortOrder: 33,
  },
  {
    slug: "hiring-coordinator",
    name: "Hiring Coordinator",
    shortDescription: "Screens candidates against stated criteria and drafts interview schedules; no automatic rejection.",
    longDescription:
      "Scores candidates against criteria you provide and drafts a schedule. It will not send rejections or offers automatically.",
    category: "operations-productivity",
    icon: "UserRoundCheck",
    tags: ["hiring", "hr"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Calendar", "Email", "ATS"],
    tools: ["create_calendar_event", "send_email", "query_database"],
    defaultInstructions:
      "Screen only against stated criteria. Never auto-reject. Never send offers. Be consistent and avoid biased language.",
    exampleTasks: ["Score these 5 resumes for a support lead role"],
    defaultTrigger: "manual",
    sortOrder: 34,
  },
  {
    slug: "internal-knowledge-assistant",
    name: "Internal Knowledge Assistant",
    shortDescription: "Answers team questions using only approved internal documents.",
    longDescription:
      "Answers from approved internal docs. If the answer is not there, it says so instead of guessing.",
    category: "operations-productivity",
    icon: "Library",
    tags: ["knowledge", "internal"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Answer only from approved documents. Do not use outside sources. Do not expose documents to people outside the workspace.",
    exampleTasks: ["What is our expense policy for client dinners?"],
    defaultTrigger: "manual",
    sortOrder: 35,
  },
  {
    slug: "invoice-extractor",
    name: "Invoice Extractor",
    shortDescription: "Extracts invoice fields into review-ready structured data.",
    longDescription:
      "Reads invoice text or fields you provide and structures vendor, amount, tax, and dates for review. It does not pay invoices.",
    category: "finance-commerce",
    icon: "Receipt",
    tags: ["invoices", "ap"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Documents", "Accounting"],
    tools: ["query_database"],
    defaultInstructions:
      "Extract fields. Do not pay. Do not change accounting records. Flag missing GSTIN or totals that do not add up.",
    exampleTasks: ["Extract fields from this invoice text"],
    defaultTrigger: "manual",
    isFeatured: true,
    sortOrder: 36,
  },
  {
    slug: "expense-categorizer",
    name: "Expense Categorizer",
    shortDescription: "Categorizes transactions and flags anomalies; does not submit transactions.",
    longDescription:
      "Categorizes expenses and flags unusual items. It does not submit reimbursements or move money.",
    category: "finance-commerce",
    icon: "Wallet",
    tags: ["expenses", "anomalies"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Accounting"],
    tools: ["query_database"],
    defaultInstructions:
      "Categorize and flag. Do not submit expenses. Do not approve payouts.",
    exampleTasks: ["Categorize these 30 card transactions"],
    defaultTrigger: "manual",
    sortOrder: 37,
  },
  {
    slug: "cash-flow-reporter",
    name: "Cash-Flow Reporter",
    shortDescription: "Creates financial summaries from read-only connected data.",
    longDescription:
      "Builds a cash-flow summary from numbers you provide or connect later in read-only mode.",
    category: "finance-commerce",
    icon: "TrendingUp",
    tags: ["cash-flow", "reporting"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Accounting"],
    tools: ["query_database"],
    defaultInstructions:
      "Summarize the provided figures. Do not transfer funds. This is not investment advice.",
    exampleTasks: ["Summarize cash in vs cash out for March"],
    defaultTrigger: "schedule",
    sortOrder: 38,
  },
  {
    slug: "subscription-audit-agent",
    name: "Subscription Audit Agent",
    shortDescription: "Identifies duplicate, unused, or expensive subscriptions.",
    longDescription:
      "Reviews a subscription list for duplicates and unused seats. It does not cancel subscriptions.",
    category: "finance-commerce",
    icon: "Repeat",
    tags: ["saas", "spend"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Accounting", "Spreadsheets"],
    tools: ["query_database"],
    defaultInstructions:
      "Recommend cancellations; do not cancel. Do not share card numbers if present — redact them.",
    exampleTasks: ["Find duplicate design-tool subscriptions"],
    defaultTrigger: "manual",
    sortOrder: 39,
  },
  {
    slug: "ecommerce-product-description-writer",
    name: "E-commerce Product Description Writer",
    shortDescription: "Produces product listing drafts.",
    longDescription:
      "Writes product title and description drafts. Publishing to a store requires approval.",
    category: "finance-commerce",
    icon: "ShoppingBag",
    tags: ["ecommerce", "copy"],
    riskLevel: "medium",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Commerce", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Draft listing copy. Do not publish. Do not invent certifications or medical claims.",
    exampleTasks: ["Write a listing for a stainless steel bottle"],
    defaultTrigger: "manual",
    sortOrder: 40,
  },
  {
    slug: "product-review-analyzer",
    name: "Product Review Analyzer",
    shortDescription: "Identifies recurring product strengths, complaints, and defects.",
    longDescription:
      "Clusters product reviews into strengths and defects. It does not reply to reviewers.",
    category: "finance-commerce",
    icon: "StarHalf",
    tags: ["reviews", "product"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Commerce", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Cluster reviews. Do not reply. Do not hide negative clusters.",
    exampleTasks: ["Analyze these 50 reviews for defect themes"],
    defaultTrigger: "manual",
    sortOrder: 41,
  },
  {
    slug: "inventory-alert-agent",
    name: "Inventory Alert Agent",
    shortDescription: "Predicts low-stock risks and recommends reorder quantities.",
    longDescription:
      "Uses sales and stock numbers you provide to recommend reorders. It does not place purchase orders.",
    category: "finance-commerce",
    icon: "Boxes",
    tags: ["inventory", "ops"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Commerce"],
    tools: ["query_database"],
    defaultInstructions:
      "Recommend reorder quantities. Do not place orders. Call out missing data instead of guessing.",
    exampleTasks: ["Which SKUs will stock out in 14 days?"],
    defaultTrigger: "schedule",
    sortOrder: 42,
  },
  {
    slug: "price-monitor",
    name: "Price Monitor",
    shortDescription: "Tracks price changes on approved competitor pages.",
    longDescription:
      "Checks approved URLs for price changes. It does not reprice your catalog automatically.",
    category: "finance-commerce",
    icon: "IndianRupee",
    tags: ["pricing", "competitors"],
    riskLevel: "low",
    estimatedSetupMinutes: 12,
    suggestedIntegrations: ["Web search", "HTTP"],
    tools: ["query_database"],
    defaultInstructions:
      "Track only approved URLs. Do not change our prices. Do not scrape behind logins.",
    exampleTasks: ["Check competitor prices for SKU-A this week"],
    defaultTrigger: "schedule",
    sortOrder: 43,
  },
  {
    slug: "purchase-order-drafting-agent",
    name: "Purchase Order Drafting Agent",
    shortDescription: "Creates purchase-order drafts; approval required before sending.",
    longDescription:
      "Drafts a purchase order from a request. Sending to a vendor requires approval. The agent starts paused.",
    category: "finance-commerce",
    icon: "FileInput",
    tags: ["procurement", "purchase-orders"],
    riskLevel: "high",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Email", "Accounting"],
    tools: ["send_email", "query_database"],
    defaultInstructions:
      "Draft the PO. Do not send until approved. Do not pay vendors. Confirm quantities against the request.",
    exampleTasks: ["Draft a PO for 200 boxes from our usual supplier"],
    defaultTrigger: "manual",
    sortOrder: 44,
  },
  {
    slug: "gst-invoice-helper",
    name: "GST Invoice Helper",
    shortDescription: "Extracts invoice information and prepares review-ready GST records.",
    longDescription:
      "Extracts GST-relevant fields (GSTIN, HSN, tax amounts) into a review table. This is not tax advice and cannot file GST returns automatically.",
    category: "finance-commerce",
    icon: "Stamp",
    tags: ["gst", "invoices", "india"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Accounting", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Extract GST fields for human review. Never file returns. Never claim this is tax advice. Flag missing GSTIN or mismatched totals.",
    exampleTasks: ["Extract GST fields from these 5 invoices for review"],
    defaultTrigger: "manual",
    sortOrder: 45,
  },
  {
    slug: "code-review-agent",
    name: "Code Review Agent",
    shortDescription: "Reviews pull requests for bugs, security concerns, and missing tests; read-only repository access by default.",
    longDescription:
      "Reviews a diff or PR description you paste. Default access is read-only. It does not merge or push code.",
    category: "developer-ai-safety",
    icon: "GitPullRequest",
    tags: ["code", "security", "review"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Git"],
    tools: ["query_database"],
    defaultInstructions:
      "Review for bugs, tests, and security issues. Do not merge. Do not push. Do not request production secrets.",
    exampleTasks: ["Review this diff for missing authorization checks"],
    defaultTrigger: "webhook",
    isFeatured: true,
    sortOrder: 46,
  },
  {
    slug: "bug-reproduction-agent",
    name: "Bug Reproduction Agent",
    shortDescription: "Turns bug reports into reproduction steps and a test plan.",
    longDescription:
      "Converts a bug report into steps, expected vs actual, and a test plan. It does not change production.",
    category: "developer-ai-safety",
    icon: "Bug",
    tags: ["qa", "bugs"],
    riskLevel: "low",
    estimatedSetupMinutes: 8,
    suggestedIntegrations: ["Git", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Write reproduction steps and tests. Do not deploy. Do not access customer production data.",
    exampleTasks: ["Turn this crash report into a QA plan"],
    defaultTrigger: "manual",
    sortOrder: 47,
  },
  {
    slug: "api-documentation-agent",
    name: "API Documentation Agent",
    shortDescription: "Generates documentation from approved code sources.",
    longDescription:
      "Drafts API docs from snippets or descriptions you approve. It does not publish docs.",
    category: "developer-ai-safety",
    icon: "Code",
    tags: ["api", "docs"],
    riskLevel: "low",
    estimatedSetupMinutes: 10,
    suggestedIntegrations: ["Git", "Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Document only approved sources. Do not invent endpoints. Do not publish. Omit secrets.",
    exampleTasks: ["Document this REST handler’s request and response"],
    defaultTrigger: "manual",
    sortOrder: 48,
  },
  {
    slug: "ai-prompt-tester",
    name: "AI Prompt Tester",
    shortDescription: "Tests prompts for jailbreak resistance, privacy exposure, and irrelevant behavior.",
    longDescription:
      "Runs structured prompt tests you define and reports weaknesses. It does not change production prompts until you approve.",
    category: "developer-ai-safety",
    icon: "FlaskConical",
    tags: ["prompts", "safety", "eval"],
    riskLevel: "medium",
    estimatedSetupMinutes: 15,
    suggestedIntegrations: ["Documents"],
    tools: ["query_database"],
    defaultInstructions:
      "Test the provided prompt. Report jailbreak, privacy, and off-topic failures. Do not store user PII from fixtures. Do not ship prompt changes automatically.",
    exampleTasks: ["Test this support prompt against 10 jailbreak attempts"],
    defaultTrigger: "manual",
    sortOrder: 49,
  },
  {
    slug: "ai-safety-monitor",
    name: "AI Safety Monitor",
    shortDescription: "Monitors agent runs for unsafe tool calls, prompt injection, PII, policy violations, and cost spikes.",
    longDescription:
      "Reviews agent run summaries you provide and flags unsafe tool use, injection attempts, PII exposure, policy issues, and unusual cost. It can recommend pause; it does not silently disable other product features.",
    category: "developer-ai-safety",
    icon: "ShieldAlert",
    tags: ["monitoring", "safety", "cost"],
    riskLevel: "medium",
    estimatedSetupMinutes: 20,
    suggestedIntegrations: ["Monitoring", "Email"],
    tools: ["query_database", "send_email"],
    defaultInstructions:
      "Flag unsafe tool calls, injection, PII, policy violations, and cost spikes. Recommend pause; do not wipe other agents. Do not include raw secrets in alerts.",
    exampleTasks: ["Review last night’s agent runs for policy violations"],
    defaultTrigger: "schedule",
    sortOrder: 50,
  },
];

export const MARKETPLACE_TEMPLATES: AgentTemplate[] = DRAFTS.map(hydrate);

export function getMarketplaceTemplateById(id: string): AgentTemplate | null {
  const needle = id.trim();
  return (
    MARKETPLACE_TEMPLATES.find(
      (template) => template.id === needle || template.slug === needle
    ) ?? null
  );
}
