import type { AgentTemplate } from "./types";

/** Fallback catalog when the templates table is unavailable (local dev / tests). */
/** Legacy 8 templates — kept for existing `template:template-N` agents. */
export const LEGACY_TEMPLATE_SEED_DATA: AgentTemplate[] = [
  {
    id: "template-1",
    name: "Refund Processor",
    description: "Issue refunds to customers",
    summary: "Automatically send refunds under ₹5,000 and notify customers",
    icon: "💰",
    category: "e-commerce",
    defaultDescription:
      "Issue refunds to customers when they request cancellations under ₹5,000 and send them confirmation emails",
    tools: ["send_email", "issue_refund"],
    triggerType: "webhook",
    supportsThreshold: true,
    defaultThreshold: 5000,
  },
  {
    id: "template-2",
    name: "Email Responder",
    description: "Auto-reply to customer emails",
    summary: "Send professional replies to customer support emails",
    icon: "📧",
    category: "support",
    defaultDescription: "Send professional replies to customer support emails",
    tools: ["send_email"],
    triggerType: "email",
    supportsThreshold: false,
    defaultThreshold: null,
  },
  {
    id: "template-3",
    name: "Appointment Scheduler",
    description: "Create customer appointments",
    summary: "Auto-schedule meetings and send calendar invites",
    icon: "📅",
    category: "service",
    defaultDescription: "Auto-schedule meetings and send calendar invites",
    tools: ["create_calendar_event", "send_email"],
    triggerType: "webhook",
    supportsThreshold: false,
    defaultThreshold: null,
  },
  {
    id: "template-4",
    name: "Lead Follow-up",
    description: "Nurture abandoned carts",
    summary: "Send personalized follow-ups to website visitors",
    icon: "🎯",
    category: "marketing",
    defaultDescription: "Send personalized follow-ups to website visitors",
    tools: ["send_email", "send_whatsapp_message"],
    triggerType: "webhook",
    supportsThreshold: false,
    defaultThreshold: null,
  },
  {
    id: "template-5",
    name: "CRM Updater",
    description: "Update customer records",
    summary: "Sync customer data from support tickets",
    icon: "👥",
    category: "operations",
    defaultDescription: "Sync customer data from support tickets",
    tools: ["update_crm_record"],
    triggerType: "webhook",
    supportsThreshold: false,
    defaultThreshold: null,
  },
  {
    id: "template-6",
    name: "Alert Monitor",
    description: "Monitor system alerts",
    summary: "Notify team when critical issues occur",
    icon: "🚨",
    category: "operations",
    defaultDescription: "Notify team when critical issues occur",
    tools: ["send_email"],
    triggerType: "webhook",
    supportsThreshold: false,
    defaultThreshold: null,
  },
  {
    id: "template-7",
    name: "Invoice Generator",
    description: "Generate and send invoices",
    summary: "Auto-create invoices for high-value orders",
    icon: "📄",
    category: "finance",
    defaultDescription: "Auto-create invoices for high-value orders",
    tools: ["send_email"],
    triggerType: "webhook",
    supportsThreshold: true,
    defaultThreshold: 10000,
  },
  {
    id: "template-8",
    name: "SMS Notifier",
    description: "Send SMS notifications",
    summary: "Alert customers via SMS for important updates",
    icon: "📱",
    category: "marketing",
    defaultDescription: "Alert customers via SMS for important updates",
    tools: ["send_whatsapp_message"],
    triggerType: "webhook",
    supportsThreshold: false,
    defaultThreshold: null,
  },
];
